---
services:
  robloxtracker:
    image: robloxtracker:latest
    build: ./
    restart: unless-stopped
    env_file: .env
    expose:
      - 8080/tcp
    networks:
      - roblox
    volumes:
      - robloxtracker-data:/data
    depends_on:
      warp-socks:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.42.0
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - roblox

  warp-socks:
    image: monius/docker-warp-socks:latest
    privileged: true
    restart: unless-stopped
    expose:
      - 9091/tcp
      - 9091/udp
    networks:
      - roblox
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.conf.all.src_valid_mark: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "https://www.cloudflare.com/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      replicas: 5

networks:
  roblox:

volumes:
  prometheus-data:
  robloxtracker-data:
